const FETCH_ERROR = "FETCH_ERROR";
const FETCH_START = "FETCH_START";
const FETCH_SUCCESS = "FETCH_SUCCESS";
const HIDE_MESSAGE = "HIDE_MESSAGE";
const SHOW_MESSAGE = "SHOW_MESSAGE";
const TOGGLE_APP_DRAWER = "TOGGLE_APP_DRAWER";
const UPDATING_CONTENT = "UPDATING_CONTENT";
export {
  FETCH_ERROR,
  FETCH_START,
  FETCH_SUCCESS,
  HIDE_MESSAGE,
  SHOW_MESSAGE,
  TOGGLE_APP_DRAWER,
  UPDATING_CONTENT,
};
