const GET_CURRENT_USER = "GET_CURRENT_USER";
const CHECK_USER_TOKEN = "CHECK_USER_TOKEN";
const SET_CURRENT_USER = "SET_CURRENT_USER";
const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
const SIGNOUT_AUTH_SUCCESS = "SIGNOUT_AUTH_SUCCESS";
const GET_ACCESS_TOKEN = "GET_ACCESS_TOKEN";
const SET_REFRESH_TOKEN = "SET_REFRESH_TOKEN";
const GET_REFRESH_TOKEN = "GET_REFRESH_TOKEN";
const SET_SUBSCRIPTION = "SET_SUBSCRIPTION";
const SET_MILESTONE = "SET_MILESTONE";
export {
  GET_CURRENT_USER,
  SET_CURRENT_USER,
  CHECK_USER_TOKEN,
  SET_REFRESH_TOKEN,
  GET_REFRESH_TOKEN,
  SET_ACCESS_TOKEN,
  GET_ACCESS_TOKEN,
  SIGNOUT_AUTH_SUCCESS,
  SET_SUBSCRIPTION,
  SET_MILESTONE,
};
